// AUTO-GENERATED by scripts/import-stock.mjs — do not edit by hand.
// Source: stock export (2026-08-09).
// Prices of 0 mean "not yet priced"; the UI shows price-on-request and
// blocks add-to-cart. rating/reviews are 0 because no reviews exist yet.

export interface ProductColor {
  name: string;
  hex: string;
  image: string;
}

export interface ProductVariant {
  size: string;
  color: string; // references a ProductColor.name; '' for colourless pieces
  quantity: number;
}

export interface Product {
  id: string;
  name: string;
  slug: string;
  price: number;
  originalPrice?: number;
  description: string;
  shortDescription: string;
  category: 'men' | 'women' | 'kids' | 'unisex';
  subcategory: string;
  fabric: string;
  colors: ProductColor[];
  sizes: string[];
  images: string[];
  tags: string[];
  featured: boolean;
  new: boolean;
  bestSeller: boolean;
  clearance?: boolean;
  rating: number;
  reviews: number;
  stock?: number;
  variants?: ProductVariant[];
}

export const products: Product[] = [
  {
    "id": "p001",
    "name": "Sowatt 1962",
    "slug": "sowatt-1962",
    "price": 0,
    "shortDescription": "Sweater",
    "description": "Sweater. Available in L, M.",
    "category": "men",
    "subcategory": "Sweater",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L",
      "M"
    ],
    "images": [
      "/products/sowatt-1962.jpg"
    ],
    "tags": [
      "sweater",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      },
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p002",
    "name": "Brooklyn 8",
    "slug": "brooklyn-8",
    "price": 0,
    "shortDescription": "Sweater",
    "description": "Sweater. Available in S, M, L.",
    "category": "men",
    "subcategory": "Sweater",
    "fabric": "",
    "colors": [],
    "sizes": [
      "S",
      "M",
      "L"
    ],
    "images": [
      "/products/brooklyn-8.jpg"
    ],
    "tags": [
      "sweater",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 4,
    "variants": [
      {
        "size": "S",
        "color": "",
        "quantity": 1
      },
      {
        "size": "M",
        "color": "",
        "quantity": 2
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p003",
    "name": "1989",
    "slug": "1989",
    "price": 0,
    "shortDescription": "Sweater",
    "description": "Sweater. Available in L, M, S. Colours: White, Black.",
    "category": "men",
    "subcategory": "Sweater",
    "fabric": "",
    "colors": [
      {
        "name": "White",
        "hex": "#FAFAFA",
        "image": ""
      },
      {
        "name": "Black",
        "hex": "#1C1917",
        "image": ""
      }
    ],
    "sizes": [
      "L",
      "M",
      "S"
    ],
    "images": [],
    "tags": [
      "sweater",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 6,
    "variants": [
      {
        "size": "L",
        "color": "White",
        "quantity": 1
      },
      {
        "size": "M",
        "color": "White",
        "quantity": 1
      },
      {
        "size": "S",
        "color": "White",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "Black",
        "quantity": 1
      },
      {
        "size": "M",
        "color": "Black",
        "quantity": 1
      },
      {
        "size": "S",
        "color": "Black",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p004",
    "name": "Elan",
    "slug": "elan",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M, L. Colours: Black.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [
      {
        "name": "Black",
        "hex": "#1C1917",
        "image": "/products/elan.jpg"
      }
    ],
    "sizes": [
      "M",
      "L"
    ],
    "images": [
      "/products/elan.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      },
      {
        "size": "M",
        "color": "Black",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p005",
    "name": "Bespirit",
    "slug": "bespirit",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/bespirit.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p006",
    "name": "RL polo",
    "slug": "rl-polo",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M, L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M",
      "L"
    ],
    "images": [
      "/products/rl-polo.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p007",
    "name": "Veliger",
    "slug": "veliger",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/veliger.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p008",
    "name": "RL light green",
    "slug": "rl-light-green",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL. Colours: light green.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [
      {
        "name": "light green",
        "hex": "#8FB07A",
        "image": "/products/rl-light-green.jpg"
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/rl-light-green.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "light green",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p009",
    "name": "RL brown",
    "slug": "rl-brown",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL. Colours: Brown.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [
      {
        "name": "Brown",
        "hex": "#7A5A42",
        "image": "/products/rl-brown.jpg"
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/rl-brown.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "Brown",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p010",
    "name": "RoyalMan Purple Stripe",
    "slug": "royalman-purple-stripe",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/royalman-purple-stripe.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p011",
    "name": "RoyalMan Blue Design",
    "slug": "royalman-blue-design",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/royalman-blue-design.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p012",
    "name": "RL sky blue",
    "slug": "rl-sky-blue",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/rl-sky-blue.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p013",
    "name": "RoyalMan Dark blue design",
    "slug": "royalman-dark-blue-design",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/royalman-dark-blue-design.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p014",
    "name": "GANT Yellow Block",
    "slug": "gant-yellow-block",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "unisex",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/gant-yellow-block.jpg"
    ],
    "tags": [
      "shirts",
      "unisex"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p015",
    "name": "US United white grey thunder",
    "slug": "us-united-white-grey-thunder",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/us-united-white-grey-thunder.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p016",
    "name": "RL Ash green",
    "slug": "rl-ash-green",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/rl-ash-green.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p017",
    "name": "RL prem Sand Brown",
    "slug": "rl-prem-sand-brown",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/rl-prem-sand-brown.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p018",
    "name": "Fable Grey",
    "slug": "fable-grey",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "unisex",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/fable-grey.jpg"
    ],
    "tags": [
      "shirts",
      "unisex"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p019",
    "name": "Catboy brown",
    "slug": "catboy-brown",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/catboy-brown.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p020",
    "name": "RL polo ash green",
    "slug": "rl-polo-ash-green",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/rl-polo-ash-green.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p021",
    "name": "Inglish black flower",
    "slug": "inglish-black-flower",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/inglish-black-flower.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p022",
    "name": "Turkey skin brown",
    "slug": "turkey-skin-brown",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/turkey-skin-brown.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p023",
    "name": "RL premium",
    "slug": "rl-premium",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/rl-premium.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p024",
    "name": "Levis Sky light blue",
    "slug": "levis-sky-light-blue",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/levis-sky-light-blue.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p025",
    "name": "RL polo blue",
    "slug": "rl-polo-blue",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/rl-polo-blue.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p026",
    "name": "Yellow flower floral",
    "slug": "yellow-flower-floral",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/yellow-flower-floral.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p027",
    "name": "Yellow black",
    "slug": "yellow-black",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/yellow-black.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p028",
    "name": "Yellow ash grey",
    "slug": "yellow-ash-grey",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/yellow-ash-grey.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p029",
    "name": "RL polo blue white stripe",
    "slug": "rl-polo-blue-white-stripe",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/rl-polo-blue-white-stripe.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 2
      }
    ]
  },
  {
    "id": "p030",
    "name": "Veliger ash green(blue design)",
    "slug": "veliger-ash-green-blue-design",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/veliger-ash-green-blue-design.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p031",
    "name": "Elan dark blue flower design",
    "slug": "elan-dark-blue-flower-design",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/elan-dark-blue-flower-design.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p032",
    "name": "Winset Tiger",
    "slug": "winset-tiger",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/winset-tiger.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p033",
    "name": "NXT green",
    "slug": "nxt-green",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/nxt-green.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p034",
    "name": "Raid Taylor",
    "slug": "raid-taylor",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/raid-taylor.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p035",
    "name": "Yellow Black Flower",
    "slug": "yellow-black-flower",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/yellow-black-flower.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p036",
    "name": "Elan Black leaf design",
    "slug": "elan-black-leaf-design",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/elan-black-leaf-design.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p037",
    "name": "RoyalMan green design",
    "slug": "royalman-green-design",
    "price": 0,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/royalman-green-design.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p038",
    "name": "Green top",
    "slug": "green-top",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in 42, 44. Colours: Green.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": "/products/green-top.jpg"
      }
    ],
    "sizes": [
      "42",
      "44"
    ],
    "images": [
      "/products/green-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "42",
        "color": "Green",
        "quantity": 1
      },
      {
        "size": "44",
        "color": "Green",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p039",
    "name": "Gold yellow top",
    "slug": "gold-yellow-top",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in M, XL. Colours: Golden Yellow.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Golden Yellow",
        "hex": "#D9A82E",
        "image": "/products/gold-yellow-top.jpg"
      }
    ],
    "sizes": [
      "M",
      "XL"
    ],
    "images": [
      "/products/gold-yellow-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "M",
        "color": "Golden Yellow",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Golden Yellow",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p040",
    "name": "Skin top",
    "slug": "skin-top",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in XL, XXL. Colours: Skin.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Skin",
        "hex": "#E3C4A8",
        "image": "/products/skin-top.jpg"
      }
    ],
    "sizes": [
      "XL",
      "XXL"
    ],
    "images": [
      "/products/skin-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "Skin",
        "quantity": 1
      },
      {
        "size": "XXL",
        "color": "Skin",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p041",
    "name": "Curry design top",
    "slug": "curry-design-top",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in XL, L.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL",
      "L"
    ],
    "images": [
      "/products/curry-design-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p042",
    "name": "White flower design top",
    "slug": "white-flower-design-top",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in XL, L.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL",
      "L"
    ],
    "images": [
      "/products/white-flower-design-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p043",
    "name": "Purple design top",
    "slug": "purple-design-top",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in XL, L.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL",
      "L"
    ],
    "images": [
      "/products/purple-design-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p044",
    "name": "Light green design top",
    "slug": "light-green-design-top",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in XL, L.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL",
      "L"
    ],
    "images": [
      "/products/light-green-design-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p045",
    "name": "Curry green design top",
    "slug": "curry-green-design-top",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in 40, 42.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [],
    "sizes": [
      "40",
      "42"
    ],
    "images": [
      "/products/curry-green-design-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "40",
        "color": "",
        "quantity": 1
      },
      {
        "size": "42",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p046",
    "name": "Dark pink top",
    "slug": "dark-pink-top",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in 40, 42.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [],
    "sizes": [
      "40",
      "42"
    ],
    "images": [
      "/products/dark-pink-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "40",
        "color": "",
        "quantity": 1
      },
      {
        "size": "42",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p047",
    "name": "Pattupavada & mirror work stiched blouse",
    "slug": "pattupavada-mirror-work-stiched-blouse",
    "price": 30,
    "shortDescription": "Blouses · Age 13-15 yrs",
    "description": "Blouses. Available in 32. Colours: Dark blue- Navy blue, Black. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [
      {
        "name": "Dark blue- Navy blue",
        "hex": "#B8B2A8",
        "image": ""
      },
      {
        "name": "Black",
        "hex": "#1C1917",
        "image": ""
      }
    ],
    "sizes": [
      "32"
    ],
    "images": [],
    "tags": [
      "blouses",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "One size",
        "color": "Dark blue- Navy blue",
        "quantity": 1
      },
      {
        "size": "32",
        "color": "Black",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p048",
    "name": "Ajarak printed Dhavani set with stiched blouse",
    "slug": "ajarak-printed-dhavani-set-with-stiched-blouse",
    "price": 35,
    "shortDescription": "Blouses",
    "description": "Blouses. Available in 34. Colours: Golden.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [
      {
        "name": "Golden",
        "hex": "#C9922E",
        "image": ""
      }
    ],
    "sizes": [
      "34"
    ],
    "images": [],
    "tags": [
      "blouses",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "34",
        "color": "Golden",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p049",
    "name": "Pattupavada with stiched blouse Red & green pearl",
    "slug": "pattupavada-with-stiched-blouse-red-green-pearl",
    "price": 15,
    "shortDescription": "Blouses · Age 10 yrs",
    "description": "Blouses. Suggested age: 10 yrs.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [],
    "tags": [
      "blouses",
      "women",
      "10 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "One size",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p050",
    "name": "Pattupavada with stiched blouse Colour Ranipink with pink",
    "slug": "pattupavada-with-stiched-blouse-colour-ranipink-with-pink",
    "price": 15,
    "shortDescription": "Blouses · Age 10 yrs",
    "description": "Blouses. Suggested age: 10 yrs.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [],
    "tags": [
      "blouses",
      "women",
      "10 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "One size",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p051",
    "name": "Pattupavada with stiched blouse",
    "slug": "pattupavada-with-stiched-blouse",
    "price": 10,
    "shortDescription": "Blouses · Age 2-5 yrs",
    "description": "Blouses. Colours: Blue, Black, Orange, Green. Suggested age: 2-5 yrs.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [
      {
        "name": "Blue",
        "hex": "#2E4A8A",
        "image": ""
      },
      {
        "name": "Black",
        "hex": "#1C1917",
        "image": ""
      },
      {
        "name": "Orange",
        "hex": "#D8792F",
        "image": ""
      },
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": ""
      }
    ],
    "sizes": [],
    "images": [],
    "tags": [
      "blouses",
      "women",
      "2-5 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 5,
    "variants": [
      {
        "size": "One size",
        "color": "Blue",
        "quantity": 1
      },
      {
        "size": "One size",
        "color": "Black",
        "quantity": 1
      },
      {
        "size": "One size",
        "color": "Orange",
        "quantity": 1
      },
      {
        "size": "One size",
        "color": "Green",
        "quantity": 2
      }
    ]
  },
  {
    "id": "p052",
    "name": "Set mundu with unstitched blouse Black",
    "slug": "set-mundu-with-unstitched-blouse-black",
    "price": 25,
    "shortDescription": "Blouses",
    "description": "Blouses. Colours: Golden pink with maroon.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [
      {
        "name": "Golden pink with maroon",
        "hex": "#B8B2A8",
        "image": ""
      }
    ],
    "sizes": [],
    "images": [],
    "tags": [
      "blouses",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "One size",
        "color": "Golden pink with maroon",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p053",
    "name": "Set mundu Golden Green with print",
    "slug": "set-mundu-golden-green-with-print",
    "price": 20,
    "shortDescription": "Mundu",
    "description": "Mundu. Colours: Golden Pink.",
    "category": "women",
    "subcategory": "Mundu",
    "fabric": "",
    "colors": [
      {
        "name": "Golden Pink",
        "hex": "#B8B2A8",
        "image": ""
      }
    ],
    "sizes": [],
    "images": [],
    "tags": [
      "mundu",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "One size",
        "color": "Golden Pink",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p054",
    "name": "Pattu Saree with Red Print",
    "slug": "pattu-saree-with-red-print",
    "price": 25,
    "shortDescription": "Sarees",
    "description": "Sarees.",
    "category": "women",
    "subcategory": "Sarees",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [],
    "tags": [
      "sarees",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "One size",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p055",
    "name": "Golden set mundu with Ajarak print unstitched blouse",
    "slug": "golden-set-mundu-with-ajarak-print-unstitched-blouse",
    "price": 20,
    "shortDescription": "Blouses",
    "description": "Blouses.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [],
    "tags": [
      "blouses",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "One size",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p056",
    "name": "Girls wear red black dot",
    "slug": "girls-wear-red-black-dot",
    "price": 15,
    "shortDescription": "Shirts · Age 5-13 yrs",
    "description": "Shirts. Available in M. Suggested age: 5-13 yrs.",
    "category": "kids",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [],
    "tags": [
      "shirts",
      "kids",
      "5-13 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p057",
    "name": "Denim Girls Wear with design",
    "slug": "denim-girls-wear-with-design",
    "price": 15,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M. Colours: Navy Blue.",
    "category": "kids",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [
      {
        "name": "Navy Blue",
        "hex": "#1E2A4A",
        "image": ""
      }
    ],
    "sizes": [
      "M"
    ],
    "images": [],
    "tags": [
      "shirts",
      "kids"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "Navy Blue",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p058",
    "name": "Cotton Shirt Girls Wear",
    "slug": "cotton-shirt-girls-wear",
    "price": 15,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "kids",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [],
    "tags": [
      "shirts",
      "kids"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p059",
    "name": "Cotton Shirt Girls Wear grey",
    "slug": "cotton-shirt-girls-wear-grey",
    "price": 15,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "kids",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [],
    "tags": [
      "shirts",
      "kids"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p060",
    "name": "Denim Jeans new design",
    "slug": "denim-jeans-new-design",
    "price": 15,
    "shortDescription": "Shirts · Age 5-13 yrs",
    "description": "Shirts. Available in M. Suggested age: 5-13 yrs.",
    "category": "kids",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [],
    "tags": [
      "shirts",
      "kids",
      "5-13 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p061",
    "name": "Girls Wear Material: Linen",
    "slug": "girls-wear-material-linen",
    "price": 20,
    "shortDescription": "Tops · Age 15 and above",
    "description": "Tops. Available in XL. Colours: Peacock Blue, Grey. Suggested age: 15 and above.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Peacock Blue",
        "hex": "#1F6F84",
        "image": ""
      },
      {
        "name": "Grey",
        "hex": "#8A8580",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "15 and above"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "Peacock Blue",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Grey",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p062",
    "name": "Girls Crop Top pink",
    "slug": "girls-crop-top-pink",
    "price": 10,
    "shortDescription": "Tops · Age 5-13 yrs",
    "description": "Tops. Available in L. Colours: Pink, White, Navy Blue, Red, Olive Green. Suggested age: 5-13 yrs.",
    "category": "kids",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Pink",
        "hex": "#D48BA0",
        "image": ""
      },
      {
        "name": "White",
        "hex": "#FAFAFA",
        "image": ""
      },
      {
        "name": "Navy Blue",
        "hex": "#1E2A4A",
        "image": ""
      },
      {
        "name": "Red",
        "hex": "#B42318",
        "image": ""
      },
      {
        "name": "Olive Green",
        "hex": "#6B6B3A",
        "image": ""
      }
    ],
    "sizes": [
      "L"
    ],
    "images": [],
    "tags": [
      "tops",
      "kids",
      "5-13 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 5,
    "variants": [
      {
        "size": "L",
        "color": "Pink",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "White",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "Navy Blue",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "Red",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "Olive Green",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p063",
    "name": "Girls Dress Material: Silk",
    "slug": "girls-dress-material-silk",
    "price": 18,
    "shortDescription": "Dresses · Age Adult",
    "description": "Dresses. Available in XL. Colours: Pink, White. Suggested age: Adult.",
    "category": "women",
    "subcategory": "Dresses",
    "fabric": "",
    "colors": [
      {
        "name": "Pink",
        "hex": "#D48BA0",
        "image": ""
      },
      {
        "name": "White",
        "hex": "#FAFAFA",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "dresses",
      "women",
      "adult"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Pink",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "White",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p064",
    "name": "Girls wear Material: Crep",
    "slug": "girls-wear-material-crep",
    "price": 22,
    "shortDescription": "Dresses",
    "description": "Dresses. Available in L. Colours: White, Parrot Green.",
    "category": "women",
    "subcategory": "Dresses",
    "fabric": "",
    "colors": [
      {
        "name": "White",
        "hex": "#FAFAFA",
        "image": ""
      },
      {
        "name": "Parrot Green",
        "hex": "#5FA84B",
        "image": ""
      }
    ],
    "sizes": [
      "L"
    ],
    "images": [],
    "tags": [
      "dresses",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "L",
        "color": "White",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "Parrot Green",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p065",
    "name": "Girls crop top Cloth- silk",
    "slug": "girls-crop-top-cloth-silk",
    "price": 0,
    "shortDescription": "Tops · Age 13-15 yrs",
    "description": "Tops. Available in XL. Colours: Golden, Green, Sky Blue. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Golden",
        "hex": "#C9922E",
        "image": ""
      },
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": ""
      },
      {
        "name": "Sky Blue",
        "hex": "#8BB8D8",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "XL",
        "color": "Golden",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Green",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Sky Blue",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p066",
    "name": "Girls crop top floral",
    "slug": "girls-crop-top-floral",
    "price": 10,
    "shortDescription": "Tops · Age 13-15 yrs",
    "description": "Tops. Colours: Green, Golden, Cherry Red. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": ""
      },
      {
        "name": "Golden",
        "hex": "#C9922E",
        "image": ""
      },
      {
        "name": "Cherry Red",
        "hex": "#9B2335",
        "image": ""
      }
    ],
    "sizes": [],
    "images": [],
    "tags": [
      "tops",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "One size",
        "color": "Green",
        "quantity": 1
      },
      {
        "size": "One size",
        "color": "Golden",
        "quantity": 1
      },
      {
        "size": "One size",
        "color": "Cherry Red",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p067",
    "name": "Girls crop top big floral",
    "slug": "girls-crop-top-big-floral",
    "price": 10,
    "shortDescription": "Tops · Age 13-15 yrs",
    "description": "Tops. Available in XL. Colours: Blueish Grey, Green, Cherry Red. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Blueish Grey",
        "hex": "#7A8A99",
        "image": ""
      },
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": ""
      },
      {
        "name": "Cherry Red",
        "hex": "#9B2335",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "XL",
        "color": "Blueish Grey",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Green",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Cherry Red",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p068",
    "name": "Girls crop top leaves",
    "slug": "girls-crop-top-leaves",
    "price": 10,
    "shortDescription": "Tops · Age 13-15 yrs",
    "description": "Tops. Available in XL. Colours: Golden, Green, Black. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Golden",
        "hex": "#C9922E",
        "image": ""
      },
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": ""
      },
      {
        "name": "Black",
        "hex": "#1C1917",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "XL",
        "color": "Golden",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Green",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Black",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p069",
    "name": "Girls crop top 2nd last",
    "slug": "girls-crop-top-2nd-last",
    "price": 10,
    "shortDescription": "Tops · Age 13-15 yrs",
    "description": "Tops. Available in XL. Colours: Cherry Red, Sky Blue, Green. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Cherry Red",
        "hex": "#9B2335",
        "image": ""
      },
      {
        "name": "Sky Blue",
        "hex": "#8BB8D8",
        "image": ""
      },
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "XL",
        "color": "Cherry Red",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Sky Blue",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Green",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p070",
    "name": "Girls crop top",
    "slug": "girls-crop-top",
    "price": 10,
    "shortDescription": "Tops · Age 13-15 yrs",
    "description": "Tops. Available in XL. Colours: Red, Olive Green, Golden Yellow. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Red",
        "hex": "#B42318",
        "image": ""
      },
      {
        "name": "Olive Green",
        "hex": "#6B6B3A",
        "image": ""
      },
      {
        "name": "Golden Yellow",
        "hex": "#D9A82E",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "XL",
        "color": "Red",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Olive Green",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Golden Yellow",
        "quantity": 1
      }
    ]
  }
];

export const collections = [
  { id: 'men',    title: "Men's",   subtitle: 'Shirts & sweaters', description: 'Shirts, polos and knitwear for every day.', image: '' },
  { id: 'women',  title: "Women's", subtitle: 'Tops & occasion',   description: 'Tops, blouses, sarees and set mundu.',      image: '' },
  { id: 'kids',   title: 'Kids',    subtitle: 'Everyday wear',     description: 'Shirts, crop tops and denim for children.', image: '' },
  { id: 'unisex', title: 'Unisex',  subtitle: 'Shared styles',     description: 'Pieces cut to suit everyone.',              image: '' },
];

/**
 * Stand-in colourway. Most pieces in the export have no colour recorded, so
 * anything reading colors[0] must fall back rather than crash.
 */
export const DEFAULT_COLOR: ProductColor = { name: 'As shown', hex: '#B8B2A8', image: '' };

/** The chosen colourway, or the stand-in when none are recorded. */
export function colorAt(p: Product, index = 0): ProductColor {
  return p.colors[index] ?? p.colors[0] ?? DEFAULT_COLOR;
}

/** True when the piece has no price set yet — show price-on-request. */
export function isUnpriced(p: Product): boolean {
  return !p.price || p.price <= 0;
}

/**
 * Units available for a size + colour. Uses the variant matrix when the product
 * has one; otherwise falls back to the single stock number (or treats stock as
 * unset → available, so pre-variant products still sell).
 */
export function variantStock(p: Product, size: string, color: string): number {
  if (p.variants && p.variants.length) {
    const match = p.variants.find((v) => v.size === size && v.color === color);
    return match ? match.quantity : 0;
  }
  return typeof p.stock === 'number' ? p.stock : Infinity;
}

/** Total units across the variant matrix, or the flat stock number. */
export function totalStock(p: Product): number {
  if (p.variants && p.variants.length) {
    return p.variants.reduce((n, v) => n + v.quantity, 0);
  }
  return typeof p.stock === 'number' ? p.stock : 0;
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getProductsByCategory(category: Product['category']): Product[] {
  return products.filter((p) => p.category === category);
}

export function getClearanceProducts(): Product[] {
  const customClearance = products.filter((p) => p.clearance && p.originalPrice && p.originalPrice > p.price);
  if (customClearance.length > 0) {
    return customClearance.sort((a, b) => discountPercent(b) - discountPercent(a));
  }
  return products.slice(0, 8).map((p, idx) => ({
    ...p,
    price: p.price || Math.round(45 + (idx * 12)),
    originalPrice: p.originalPrice || Math.round((p.price || (45 + (idx * 12))) * 1.4),
    clearance: true,
  }));
}

export function discountPercent(p: Product): number {
  if (!p.originalPrice || p.originalPrice <= p.price) return 0;
  return Math.round(((p.originalPrice - p.price) / p.originalPrice) * 100);
}

export const testimonials: {
  id: string; name: string; location: string; text: string; rating: number; product: string;
}[] = [];
