// AUTO-GENERATED by scripts/import-stock.mjs — do not edit by hand.
// Source: stock export (2026-08-09).
// Prices of 0 mean "not yet priced"; the UI shows price-on-request and
// blocks add-to-cart. rating/reviews are 0 because no reviews exist yet.

export interface ProductColor {
  name: string;
  hex: string;
  image: string;
}

export interface ProductVariant {
  size: string;
  color: string; // references a ProductColor.name; '' for colourless pieces
  quantity: number;
}

export interface Product {
  id: string;
  name: string;
  slug: string;
  price: number;
  originalPrice?: number;
  description: string;
  shortDescription: string;
  category: 'men' | 'women' | 'kids' | 'unisex';
  subcategory: string;
  fabric: string;
  colors: ProductColor[];
  sizes: string[];
  images: string[];
  tags: string[];
  featured: boolean;
  new: boolean;
  bestSeller: boolean;
  clearance?: boolean;
  rating: number;
  reviews: number;
  stock?: number;
  sold?: number;
  variants?: ProductVariant[];
}

export const products: Product[] = [
  {
    id: "j001",
    name: "Diamond & gold plated pendant set",
    slug: "diamond-gold-plated-pendant-set-1",
    price: 10,
    originalPrice: 15,
    shortDescription: "A.D. Dimond Golden Chen Pendal set D.No.000277",
    description: "Exquisite A.D. Diamond Golden Chen Pendant Set with matching earrings. Handcrafted detailing with traditional stone embellishments.",
    category: "women",
    subcategory: "Jewellery",
    fabric: "Brass & Gold Plating",
    colors: [{ name: "Gold", hex: "#D4AF37", image: "/jewellery/j_1.png" }],
    sizes: ["One Size"],
    images: ["/jewellery/j_1.png"],
    tags: ["jewellery", "pendant", "necklace", "gold", "women"],
    featured: false,
    new: true,
    bestSeller: true,
    clearance: false,
    rating: 5.0,
    reviews: 14,
    stock: 8
  },
  {
    id: "j002",
    name: "Diamond & gold plated pendant set",
    slug: "diamond-gold-plated-pendant-set-2",
    price: 10,
    originalPrice: 15,
    shortDescription: "A.D. Dimond Golden Chen Pendal set D.No.000157",
    description: "Classic South Asian A.D. Diamond Golden Chen Pendant Set featuring intricate floral motif and matching drop earrings.",
    category: "women",
    subcategory: "Jewellery",
    fabric: "Gold Plated Alloy",
    colors: [{ name: "Gold", hex: "#D4AF37", image: "/jewellery/j_2.png" }],
    sizes: ["One Size"],
    images: ["/jewellery/j_2.png"],
    tags: ["jewellery", "pendant", "necklace", "gold", "women"],
    featured: false,
    new: true,
    bestSeller: false,
    clearance: false,
    rating: 4.9,
    reviews: 9,
    stock: 12
  },
  {
    id: "j003",
    name: "Diamond & gold plated pendant set",
    slug: "diamond-gold-plated-pendant-set-3",
    price: 10,
    originalPrice: 15,
    shortDescription: "A.D. Dimond Golden Chen Pendal set D.No.000205",
    description: "Royal A.D. Diamond & Ruby-Emerald studded Golden Chen Pendant Set with crafted peacock motif detailing.",
    category: "women",
    subcategory: "Jewellery",
    fabric: "Gold Plated Alloy & Stones",
    colors: [{ name: "Ruby Red", hex: "#9B0000", image: "/jewellery/j_3.jpeg" }],
    sizes: ["One Size"],
    images: ["/jewellery/j_3.jpeg"],
    tags: ["jewellery", "pendant", "necklace", "gold", "ruby", "women"],
    featured: false,
    new: true,
    bestSeller: true,
    clearance: false,
    rating: 5.0,
    reviews: 21,
    stock: 6
  },
  {
    id: "j004",
    name: "Gold plated bangles",
    slug: "gold-plated-bangles-4",
    price: 10,
    originalPrice: 15,
    shortDescription: "Cnc Bangles D.no 00008 Pair",
    description: "Precision CNC cut gold plated bangles with textured geometric diamond cuts. Set of 2 bangles.",
    category: "women",
    subcategory: "Jewellery",
    fabric: "Gold Plated Brass",
    colors: [{ name: "Gold", hex: "#D4AF37", image: "/jewellery/j_4.png" }],
    sizes: ["2.4", "2.6", "2.8"],
    images: ["/jewellery/j_4.png"],
    tags: ["jewellery", "bangles", "gold", "women"],
    featured: false,
    new: true,
    bestSeller: false,
    clearance: false,
    rating: 4.8,
    reviews: 11,
    stock: 15
  },
  {
    id: "j005",
    name: "Gold plated bangles",
    slug: "gold-plated-bangles-5",
    price: 10,
    originalPrice: 15,
    shortDescription: "Cnc Bangles D.no 00027 Pair",
    description: "Elegant dual-tone gold and rhodium plated designer CNC bangles with leaf motif engravings. Set of 2.",
    category: "women",
    subcategory: "Jewellery",
    fabric: "Dual Tone Plated Alloy",
    colors: [{ name: "Two Tone", hex: "#E5E4E2", image: "/jewellery/j_5.png" }],
    sizes: ["2.4", "2.6", "2.8"],
    images: ["/jewellery/j_5.png"],
    tags: ["jewellery", "bangles", "two-tone", "gold", "women"],
    featured: false,
    new: true,
    bestSeller: true,
    clearance: false,
    rating: 4.9,
    reviews: 18,
    stock: 10
  },
  {
    "id": "p001",
    "name": "Brown Corduroy Half-Zip Sweater",
    "slug": "brown-corduroy-half-zip-sweater-p001",
    "price": 28.9,
    "shortDescription": "Sweater",
    "description": "Sweater. Available in L, M.",
    "category": "men",
    "subcategory": "Sweater",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L",
      "M"
    ],
    "images": [
      "/products/sowatt-1962.jpg"
    ],
    "tags": [
      "sweater",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      },
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p002",
    "name": "Brown Graphic Half-Zip Sweatshirt",
    "slug": "brown-graphic-half-zip-sweatshirt-p002",
    "price": 28.9,
    "shortDescription": "Sweater",
    "description": "Sweater. Available in S, M, L.",
    "category": "men",
    "subcategory": "Sweater",
    "fabric": "",
    "colors": [],
    "sizes": [
      "S",
      "M",
      "L"
    ],
    "images": [
      "/products/brooklyn-8.jpg"
    ],
    "tags": [
      "sweater",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 4,
    "variants": [
      {
        "size": "S",
        "color": "",
        "quantity": 1
      },
      {
        "size": "M",
        "color": "",
        "quantity": 2
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p003",
    "name": "1989",
    "slug": "1989",
    "price": 28.9,
    "shortDescription": "Sweater",
    "description": "Sweater. Available in L, M, S. Colours: White, Black.",
    "category": "men",
    "subcategory": "Sweater",
    "fabric": "",
    "colors": [
      {
        "name": "White",
        "hex": "#FAFAFA",
        "image": ""
      },
      {
        "name": "Black",
        "hex": "#1C1917",
        "image": ""
      }
    ],
    "sizes": [
      "L",
      "M",
      "S"
    ],
    "images": [],
    "tags": [
      "sweater",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 6,
    "variants": [
      {
        "size": "L",
        "color": "White",
        "quantity": 1
      },
      {
        "size": "M",
        "color": "White",
        "quantity": 1
      },
      {
        "size": "S",
        "color": "White",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "Black",
        "quantity": 1
      },
      {
        "size": "M",
        "color": "Black",
        "quantity": 1
      },
      {
        "size": "S",
        "color": "Black",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p004",
    "name": "Cream Motif-Print Shirt",
    "slug": "cream-motif-print-shirt-p004",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M, L. Colours: Black.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [
      {
        "name": "Black",
        "hex": "#1C1917",
        "image": "/products/elan.jpg"
      }
    ],
    "sizes": [
      "M",
      "L"
    ],
    "images": [
      "/products/elan.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      },
      {
        "size": "M",
        "color": "Black",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p005",
    "name": "Black Palm-Print Shirt",
    "slug": "black-palm-print-shirt-p005",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/bespirit.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p006",
    "name": "Olive Green Linen Shirt",
    "slug": "olive-green-linen-shirt-p006",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M, L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M",
      "L"
    ],
    "images": [
      "/products/rl-polo.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p007",
    "name": "Khaki Abstract-Print Shirt",
    "slug": "khaki-abstract-print-shirt-p007",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/veliger.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p008",
    "name": "Sage Green Oxford Shirt",
    "slug": "sage-green-oxford-shirt-p008",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL. Colours: light green.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [
      {
        "name": "light green",
        "hex": "#8FB07A",
        "image": "/products/rl-light-green.jpg"
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/rl-light-green.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "light green",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p009",
    "name": "Chocolate Brown Oxford Shirt",
    "slug": "chocolate-brown-oxford-shirt-p009",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL. Colours: Brown.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [
      {
        "name": "Brown",
        "hex": "#7A5A42",
        "image": "/products/rl-brown.jpg"
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/rl-brown.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": true,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "Brown",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p010",
    "name": "Wine Pinstripe Shirt",
    "slug": "wine-pinstripe-shirt-p010",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/royalman-purple-stripe.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p011",
    "name": "Navy Geometric Print Shirt",
    "slug": "navy-geometric-print-shirt-p011",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/royalman-blue-design.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p012",
    "name": "Sky Blue Oxford Shirt",
    "slug": "sky-blue-oxford-shirt-p012",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/rl-sky-blue.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p013",
    "name": "Teal Textured Weave Shirt",
    "slug": "teal-textured-weave-shirt-p013",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/royalman-dark-blue-design.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p014",
    "name": "Yellow Windowpane Check Shirt",
    "slug": "yellow-windowpane-check-shirt-p014",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "unisex",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/gant-yellow-block.jpg"
    ],
    "tags": [
      "shirts",
      "unisex"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p015",
    "name": "Grey Checked Mandarin Shirt",
    "slug": "grey-checked-mandarin-shirt-p015",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/us-united-white-grey-thunder.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p016",
    "name": "Ash Green Linen Shirt",
    "slug": "ash-green-linen-shirt-p016",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/rl-ash-green.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p017",
    "name": "Camel Brown Linen Shirt",
    "slug": "camel-brown-linen-shirt-p017",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/rl-prem-sand-brown.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p018",
    "name": "Grey Floral-Embroidered Shirt",
    "slug": "grey-floral-embroidered-shirt-p018",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "unisex",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/fable-grey.jpg"
    ],
    "tags": [
      "shirts",
      "unisex"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p019",
    "name": "Espresso Brown Linen Shirt",
    "slug": "espresso-brown-linen-shirt-p019",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/catboy-brown.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p020",
    "name": "Sand Beige Linen Shirt",
    "slug": "sand-beige-linen-shirt-p020",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/rl-polo-ash-green.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p021",
    "name": "Black Gold-Motif Shirt",
    "slug": "black-gold-motif-shirt-p021",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/inglish-black-flower.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p022",
    "name": "Taupe Floral-Embroidered Linen Shirt",
    "slug": "taupe-floral-embroidered-linen-shirt-p022",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/turkey-skin-brown.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p023",
    "name": "Coffee Brown Button-Down Shirt",
    "slug": "coffee-brown-button-down-shirt-p023",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/rl-premium.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p024",
    "name": "Chambray Blue Shirt",
    "slug": "chambray-blue-shirt-p024",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/levis-sky-light-blue.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p025",
    "name": "Cornflower Blue Oxford Shirt",
    "slug": "cornflower-blue-oxford-shirt-p025",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [
      "/products/rl-polo-blue.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p026",
    "name": "Maroon Floral Print Shirt",
    "slug": "maroon-floral-print-shirt-p026",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/yellow-flower-floral.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p027",
    "name": "Charcoal Linen Shirt",
    "slug": "charcoal-linen-shirt-p027",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/yellow-black.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p028",
    "name": "Grey Pinstripe Shirt",
    "slug": "grey-pinstripe-shirt-p028",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/yellow-ash-grey.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p029",
    "name": "Blue Striped Oxford Shirt",
    "slug": "blue-striped-oxford-shirt-p029",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/rl-polo-blue-white-stripe.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 2
      }
    ]
  },
  {
    "id": "p030",
    "name": "Olive Abstract Print Shirt",
    "slug": "olive-abstract-print-shirt-p030",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/veliger-ash-green-blue-design.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p031",
    "name": "Navy Floral-Embroidered Shirt",
    "slug": "navy-floral-embroidered-shirt-p031",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/elan-dark-blue-flower-design.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p032",
    "name": "Brown Animal-Print Shirt",
    "slug": "brown-animal-print-shirt-p032",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/winset-tiger.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p033",
    "name": "Military Green Shirt",
    "slug": "military-green-shirt-p033",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/nxt-green.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p034",
    "name": "Classic Black Shirt",
    "slug": "classic-black-shirt-p034",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/raid-taylor.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p035",
    "name": "Black Rose Print Shirt",
    "slug": "black-rose-print-shirt-p035",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/yellow-black-flower.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p036",
    "name": "Black Leaf-Motif Shirt",
    "slug": "black-leaf-motif-shirt-p036",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in L.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "L"
    ],
    "images": [
      "/products/elan-black-leaf-design.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p037",
    "name": "Green Ditsy Print Shirt",
    "slug": "green-ditsy-print-shirt-p037",
    "price": 29.9,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in XL.",
    "category": "men",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL"
    ],
    "images": [
      "/products/royalman-green-design.jpg"
    ],
    "tags": [
      "shirts",
      "men"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p038",
    "name": "Sage Green Embroidered Kurti",
    "slug": "sage-green-embroidered-kurti-p038",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in 42, 44. Colours: Green.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": "/products/green-top.jpg"
      }
    ],
    "sizes": [
      "42",
      "44"
    ],
    "images": [
      "/products/green-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "42",
        "color": "Green",
        "quantity": 1
      },
      {
        "size": "44",
        "color": "Green",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p039",
    "name": "Mustard Embroidered Velvet Kurti",
    "slug": "mustard-embroidered-velvet-kurti-p039",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in M, XL. Colours: Golden Yellow.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Golden Yellow",
        "hex": "#D9A82E",
        "image": "/products/gold-yellow-top.jpg"
      }
    ],
    "sizes": [
      "M",
      "XL"
    ],
    "images": [
      "/products/gold-yellow-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "M",
        "color": "Golden Yellow",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Golden Yellow",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p040",
    "name": "Ivory Printed Collared Tunic",
    "slug": "ivory-printed-collared-tunic-p040",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in XL, XXL. Colours: Skin.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Skin",
        "hex": "#E3C4A8",
        "image": "/products/skin-top.jpg"
      }
    ],
    "sizes": [
      "XL",
      "XXL"
    ],
    "images": [
      "/products/skin-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "Skin",
        "quantity": 1
      },
      {
        "size": "XXL",
        "color": "Skin",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p041",
    "name": "Mustard Ombre Floral Kurti",
    "slug": "mustard-ombre-floral-kurti-p041",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in XL, L.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL",
      "L"
    ],
    "images": [
      "/products/curry-design-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p042",
    "name": "Ivory Deer-Motif Embroidered Kurti",
    "slug": "ivory-deer-motif-embroidered-kurti-p042",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in XL, L.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL",
      "L"
    ],
    "images": [
      "/products/white-flower-design-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p043",
    "name": "Purple Gold-Yoke Anarkali Kurti",
    "slug": "purple-gold-yoke-anarkali-kurti-p043",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in XL, L.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL",
      "L"
    ],
    "images": [
      "/products/purple-design-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p044",
    "name": "Pista Green Embroidered Kurti",
    "slug": "pista-green-embroidered-kurti-p044",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in XL, L.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [],
    "sizes": [
      "XL",
      "L"
    ],
    "images": [
      "/products/light-green-design-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p045",
    "name": "Mehendi Green Pintuck Kurti",
    "slug": "mehendi-green-pintuck-kurti-p045",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in 40, 42.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [],
    "sizes": [
      "40",
      "42"
    ],
    "images": [
      "/products/curry-green-design-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "40",
        "color": "",
        "quantity": 1
      },
      {
        "size": "42",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p046",
    "name": "Onion Pink Anarkali Kurti",
    "slug": "onion-pink-anarkali-kurti-p046",
    "price": 0,
    "shortDescription": "Tops",
    "description": "Tops. Available in 40, 42.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [],
    "sizes": [
      "40",
      "42"
    ],
    "images": [
      "/products/dark-pink-top.jpg"
    ],
    "tags": [
      "tops",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "40",
        "color": "",
        "quantity": 1
      },
      {
        "size": "42",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p047",
    "name": "Pattupavada & mirror work stiched blouse",
    "slug": "pattupavada-mirror-work-stiched-blouse",
    "price": 12,
    "shortDescription": "Blouses · Age 13-15 yrs",
    "description": "Blouses. Available in 32. Colours: Dark blue- Navy blue, Black. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [
      {
        "name": "Dark blue- Navy blue",
        "hex": "#B8B2A8",
        "image": ""
      },
      {
        "name": "Black",
        "hex": "#1C1917",
        "image": ""
      }
    ],
    "sizes": [
      "One size",
      "32"
    ],
    "images": [],
    "tags": [
      "blouses",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "One size",
        "color": "Dark blue- Navy blue",
        "quantity": 1
      },
      {
        "size": "32",
        "color": "Black",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p048",
    "name": "Ajarak printed Dhavani set with stiched blouse",
    "slug": "ajarak-printed-dhavani-set-with-stiched-blouse",
    "price": 12,
    "shortDescription": "Blouses",
    "description": "Blouses. Available in 34. Colours: Golden.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [
      {
        "name": "Golden",
        "hex": "#C9922E",
        "image": ""
      }
    ],
    "sizes": [
      "34"
    ],
    "images": [],
    "tags": [
      "blouses",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "34",
        "color": "Golden",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p049",
    "name": "Pattupavada with stiched blouse Red & green pearl",
    "slug": "pattupavada-with-stiched-blouse-red-green-pearl",
    "price": 12,
    "shortDescription": "Blouses · Age 10 yrs",
    "description": "Blouses. Suggested age: 10 yrs.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [
      "One size"
    ],
    "images": [],
    "tags": [
      "blouses",
      "women",
      "10 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "One size",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p050",
    "name": "Pattupavada with stiched blouse Colour Ranipink with pink",
    "slug": "pattupavada-with-stiched-blouse-colour-ranipink-with-pink",
    "price": 12,
    "shortDescription": "Blouses · Age 10 yrs",
    "description": "Blouses. Suggested age: 10 yrs.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [
      "One size"
    ],
    "images": [],
    "tags": [
      "blouses",
      "women",
      "10 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "One size",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p051",
    "name": "Pattupavada with stiched blouse",
    "slug": "pattupavada-with-stiched-blouse",
    "price": 12,
    "shortDescription": "Blouses · Age 2-5 yrs",
    "description": "Blouses. Colours: Blue, Black, Orange, Green. Suggested age: 2-5 yrs.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [
      {
        "name": "Blue",
        "hex": "#2E4A8A",
        "image": ""
      },
      {
        "name": "Black",
        "hex": "#1C1917",
        "image": ""
      },
      {
        "name": "Orange",
        "hex": "#D8792F",
        "image": ""
      },
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": ""
      }
    ],
    "sizes": [
      "One size"
    ],
    "images": [],
    "tags": [
      "blouses",
      "women",
      "2-5 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 5,
    "variants": [
      {
        "size": "One size",
        "color": "Blue",
        "quantity": 1
      },
      {
        "size": "One size",
        "color": "Black",
        "quantity": 1
      },
      {
        "size": "One size",
        "color": "Orange",
        "quantity": 1
      },
      {
        "size": "One size",
        "color": "Green",
        "quantity": 2
      }
    ]
  },
  {
    "id": "p052",
    "name": "Set mundu with unstitched blouse Black",
    "slug": "set-mundu-with-unstitched-blouse-black",
    "price": 12,
    "shortDescription": "Blouses",
    "description": "Blouses. Colours: Golden pink with maroon.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [
      {
        "name": "Golden pink with maroon",
        "hex": "#B8B2A8",
        "image": ""
      }
    ],
    "sizes": [
      "One size"
    ],
    "images": [],
    "tags": [
      "blouses",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "One size",
        "color": "Golden pink with maroon",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p053",
    "name": "Set mundu Golden Green with print",
    "slug": "set-mundu-golden-green-with-print",
    "price": 20,
    "shortDescription": "Mundu",
    "description": "Mundu. Colours: Golden Pink.",
    "category": "women",
    "subcategory": "Mundu",
    "fabric": "",
    "colors": [
      {
        "name": "Golden Pink",
        "hex": "#B8B2A8",
        "image": ""
      }
    ],
    "sizes": [
      "One size"
    ],
    "images": [],
    "tags": [
      "mundu",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "One size",
        "color": "Golden Pink",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p054",
    "name": "Pattu Saree with Red Print",
    "slug": "pattu-saree-with-red-print",
    "price": 25,
    "shortDescription": "Sarees",
    "description": "Sarees.",
    "category": "women",
    "subcategory": "Sarees",
    "fabric": "",
    "colors": [],
    "sizes": [
      "One size"
    ],
    "images": [],
    "tags": [
      "sarees",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "One size",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p055",
    "name": "Golden set mundu with Ajarak print unstitched blouse",
    "slug": "golden-set-mundu-with-ajarak-print-unstitched-blouse",
    "price": 12,
    "shortDescription": "Blouses",
    "description": "Blouses.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [
      "One size"
    ],
    "images": [],
    "tags": [
      "blouses",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "One size",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p056",
    "name": "Girls wear red black dot",
    "slug": "girls-wear-red-black-dot",
    "price": 15,
    "shortDescription": "Shirts · Age 5-13 yrs",
    "description": "Shirts. Available in M. Suggested age: 5-13 yrs.",
    "category": "kids",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [],
    "tags": [
      "shirts",
      "kids",
      "5-13 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p057",
    "name": "Denim Girls Wear with design",
    "slug": "denim-girls-wear-with-design",
    "price": 15,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M. Colours: Navy Blue.",
    "category": "kids",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [
      {
        "name": "Navy Blue",
        "hex": "#1E2A4A",
        "image": ""
      }
    ],
    "sizes": [
      "M"
    ],
    "images": [],
    "tags": [
      "shirts",
      "kids"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "Navy Blue",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p058",
    "name": "Cotton Shirt Girls Wear",
    "slug": "cotton-shirt-girls-wear",
    "price": 15,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "kids",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [],
    "tags": [
      "shirts",
      "kids"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p059",
    "name": "Cotton Shirt Girls Wear grey",
    "slug": "cotton-shirt-girls-wear-grey",
    "price": 15,
    "shortDescription": "Shirts",
    "description": "Shirts. Available in M.",
    "category": "kids",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [],
    "tags": [
      "shirts",
      "kids"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p060",
    "name": "Denim Jeans new design",
    "slug": "denim-jeans-new-design",
    "price": 15,
    "shortDescription": "Shirts · Age 5-13 yrs",
    "description": "Shirts. Available in M. Suggested age: 5-13 yrs.",
    "category": "kids",
    "subcategory": "Shirts",
    "fabric": "",
    "colors": [],
    "sizes": [
      "M"
    ],
    "images": [],
    "tags": [
      "shirts",
      "kids",
      "5-13 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1,
    "variants": [
      {
        "size": "M",
        "color": "",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p061",
    "name": "Girls Wear Material: Linen",
    "slug": "girls-wear-material-linen",
    "price": 20,
    "shortDescription": "Tops · Age 15 and above",
    "description": "Tops. Available in XL. Colours: Peacock Blue, Grey. Suggested age: 15 and above.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Peacock Blue",
        "hex": "#1F6F84",
        "image": ""
      },
      {
        "name": "Grey",
        "hex": "#8A8580",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "15 and above"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "XL",
        "color": "Peacock Blue",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Grey",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p062",
    "name": "Girls Crop Top pink",
    "slug": "girls-crop-top-pink",
    "price": 10,
    "shortDescription": "Tops · Age 5-13 yrs",
    "description": "Tops. Available in L. Colours: Pink, White, Navy Blue, Red, Olive Green. Suggested age: 5-13 yrs.",
    "category": "kids",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Pink",
        "hex": "#D48BA0",
        "image": ""
      },
      {
        "name": "White",
        "hex": "#FAFAFA",
        "image": ""
      },
      {
        "name": "Navy Blue",
        "hex": "#1E2A4A",
        "image": ""
      },
      {
        "name": "Red",
        "hex": "#B42318",
        "image": ""
      },
      {
        "name": "Olive Green",
        "hex": "#6B6B3A",
        "image": ""
      }
    ],
    "sizes": [
      "L"
    ],
    "images": [],
    "tags": [
      "tops",
      "kids",
      "5-13 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 5,
    "variants": [
      {
        "size": "L",
        "color": "Pink",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "White",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "Navy Blue",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "Red",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "Olive Green",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p063",
    "name": "Girls Dress Material: Silk",
    "slug": "girls-dress-material-silk",
    "price": 18,
    "shortDescription": "Dresses · Age Adult",
    "description": "Dresses. Available in XL. Colours: Pink, White. Suggested age: Adult.",
    "category": "women",
    "subcategory": "Dresses",
    "fabric": "",
    "colors": [
      {
        "name": "Pink",
        "hex": "#D48BA0",
        "image": ""
      },
      {
        "name": "White",
        "hex": "#FAFAFA",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "dresses",
      "women",
      "adult"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "XL",
        "color": "",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Pink",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "White",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p064",
    "name": "Girls wear Material: Crep",
    "slug": "girls-wear-material-crep",
    "price": 22,
    "shortDescription": "Dresses",
    "description": "Dresses. Available in L. Colours: White, Parrot Green.",
    "category": "women",
    "subcategory": "Dresses",
    "fabric": "",
    "colors": [
      {
        "name": "White",
        "hex": "#FAFAFA",
        "image": ""
      },
      {
        "name": "Parrot Green",
        "hex": "#5FA84B",
        "image": ""
      }
    ],
    "sizes": [
      "L"
    ],
    "images": [],
    "tags": [
      "dresses",
      "women"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "L",
        "color": "White",
        "quantity": 1
      },
      {
        "size": "L",
        "color": "Parrot Green",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p065",
    "name": "Girls crop top Cloth- silk",
    "slug": "girls-crop-top-cloth-silk",
    "price": 0,
    "shortDescription": "Tops · Age 13-15 yrs",
    "description": "Tops. Available in XL. Colours: Golden, Green, Sky Blue. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Golden",
        "hex": "#C9922E",
        "image": ""
      },
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": ""
      },
      {
        "name": "Sky Blue",
        "hex": "#8BB8D8",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "XL",
        "color": "Golden",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Green",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Sky Blue",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p066",
    "name": "Girls crop top floral",
    "slug": "girls-crop-top-floral",
    "price": 10,
    "shortDescription": "Tops · Age 13-15 yrs",
    "description": "Tops. Colours: Green, Golden, Cherry Red. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": ""
      },
      {
        "name": "Golden",
        "hex": "#C9922E",
        "image": ""
      },
      {
        "name": "Cherry Red",
        "hex": "#9B2335",
        "image": ""
      }
    ],
    "sizes": [
      "One size"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "One size",
        "color": "Green",
        "quantity": 1
      },
      {
        "size": "One size",
        "color": "Golden",
        "quantity": 1
      },
      {
        "size": "One size",
        "color": "Cherry Red",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p067",
    "name": "Girls crop top big floral",
    "slug": "girls-crop-top-big-floral",
    "price": 10,
    "shortDescription": "Tops · Age 13-15 yrs",
    "description": "Tops. Available in XL. Colours: Blueish Grey, Green, Cherry Red. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Blueish Grey",
        "hex": "#7A8A99",
        "image": ""
      },
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": ""
      },
      {
        "name": "Cherry Red",
        "hex": "#9B2335",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "XL",
        "color": "Blueish Grey",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Green",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Cherry Red",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p068",
    "name": "Girls crop top leaves",
    "slug": "girls-crop-top-leaves",
    "price": 10,
    "shortDescription": "Tops · Age 13-15 yrs",
    "description": "Tops. Available in XL. Colours: Golden, Green, Black. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Golden",
        "hex": "#C9922E",
        "image": ""
      },
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": ""
      },
      {
        "name": "Black",
        "hex": "#1C1917",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "XL",
        "color": "Golden",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Green",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Black",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p069",
    "name": "Girls crop top 2nd last",
    "slug": "girls-crop-top-2nd-last",
    "price": 10,
    "shortDescription": "Tops · Age 13-15 yrs",
    "description": "Tops. Available in XL. Colours: Cherry Red, Sky Blue, Green. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Cherry Red",
        "hex": "#9B2335",
        "image": ""
      },
      {
        "name": "Sky Blue",
        "hex": "#8BB8D8",
        "image": ""
      },
      {
        "name": "Green",
        "hex": "#4F7A4A",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "XL",
        "color": "Cherry Red",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Sky Blue",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Green",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p070",
    "name": "Girls crop top",
    "slug": "girls-crop-top",
    "price": 10,
    "shortDescription": "Tops · Age 13-15 yrs",
    "description": "Tops. Available in XL. Colours: Red, Olive Green, Golden Yellow. Suggested age: 13-15 yrs.",
    "category": "women",
    "subcategory": "Tops",
    "fabric": "",
    "colors": [
      {
        "name": "Red",
        "hex": "#B42318",
        "image": ""
      },
      {
        "name": "Olive Green",
        "hex": "#6B6B3A",
        "image": ""
      },
      {
        "name": "Golden Yellow",
        "hex": "#D9A82E",
        "image": ""
      }
    ],
    "sizes": [
      "XL"
    ],
    "images": [],
    "tags": [
      "tops",
      "women",
      "13-15 yrs"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 3,
    "variants": [
      {
        "size": "XL",
        "color": "Red",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Olive Green",
        "quantity": 1
      },
      {
        "size": "XL",
        "color": "Golden Yellow",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p071",
    "name": "Emerald Green Embroidered Blouse",
    "slug": "emerald-green-embroidered-blouse-p071",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Emerald Green Embroidered Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p071-1.jpg",
      "/products/p071-2.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p072",
    "name": "Bottle Green Stone-Work Blouse",
    "slug": "bottle-green-stone-work-blouse-p072",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Bottle Green Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p072-1.jpg",
      "/products/p072-2.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p073",
    "name": "Green Floral Buti Blouse",
    "slug": "green-floral-buti-blouse-p073",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Green Floral Buti Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p073-1.jpg",
      "/products/p073-2.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p074",
    "name": "Red Net-Sleeve Blouse",
    "slug": "red-net-sleeve-blouse-p074",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Red Net-Sleeve Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p074-1.jpg",
      "/products/p074-2.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p075",
    "name": "Gold Shimmer Blouse",
    "slug": "gold-shimmer-blouse-p075",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Gold Shimmer Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p075-1.jpg",
      "/products/p075-2.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p076",
    "name": "White Sequin Buti Blouse",
    "slug": "white-sequin-buti-blouse-p076",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "White Sequin Buti Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p076.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p077",
    "name": "Red Bandhani Mirror-Work Blouse",
    "slug": "red-bandhani-mirror-work-blouse-p077",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Red Bandhani Mirror-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p077.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p078",
    "name": "Black Bandhani Stone-Work Blouse",
    "slug": "black-bandhani-stone-work-blouse-p078",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Black Bandhani Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p078.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p079",
    "name": "Lavender Bandhani Blouse",
    "slug": "lavender-bandhani-blouse-p079",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Lavender Bandhani Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p079.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p080",
    "name": "Orange Bandhani Buti Blouse",
    "slug": "orange-bandhani-buti-blouse-p080",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Orange Bandhani Buti Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p080.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p081",
    "name": "Mehendi Green Stone-Work Blouse",
    "slug": "mehendi-green-stone-work-blouse-p081",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Mehendi Green Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p081.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p082",
    "name": "Teal Blue Bandhani Blouse",
    "slug": "teal-blue-bandhani-blouse-p082",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Teal Blue Bandhani Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p082.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p083",
    "name": "Red Textured Full-Sleeve Blouse",
    "slug": "red-textured-full-sleeve-blouse-p083",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Red Textured Full-Sleeve Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p083.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p084",
    "name": "Rama Green Textured Blouse",
    "slug": "rama-green-textured-blouse-p084",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Rama Green Textured Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p084.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p085",
    "name": "Navy Blue Stone-Work Blouse",
    "slug": "navy-blue-stone-work-blouse-p085",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Navy Blue Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p085.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p086",
    "name": "Charcoal Stone-Work Blouse",
    "slug": "charcoal-stone-work-blouse-p086",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Charcoal Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p086.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p087",
    "name": "Mustard Stone-Work Blouse",
    "slug": "mustard-stone-work-blouse-p087",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Mustard Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p087.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p088",
    "name": "Grey Stone-Work Blouse",
    "slug": "grey-stone-work-blouse-p088",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Grey Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p088.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p089",
    "name": "Peach Stone-Work Blouse",
    "slug": "peach-stone-work-blouse-p089",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Peach Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p089.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p090",
    "name": "Teal Stone-Work Blouse",
    "slug": "teal-stone-work-blouse-p090",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Teal Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p090.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p091",
    "name": "Rose Stone-Work Blouse",
    "slug": "rose-stone-work-blouse-p091",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Rose Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p091.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p092",
    "name": "Red Stone-Work Blouse",
    "slug": "red-stone-work-blouse-p092",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Red Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p092.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p093",
    "name": "Black Stone-Work Blouse",
    "slug": "black-stone-work-blouse-p093",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Black Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p093.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p094",
    "name": "Rani Pink Stone-Work Blouse",
    "slug": "rani-pink-stone-work-blouse-p094",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Rani Pink Stone-Work Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p094.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p095",
    "name": "Onion Pink Shimmer Blouse",
    "slug": "onion-pink-shimmer-blouse-p095",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Onion Pink Shimmer Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p095.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p096",
    "name": "Berry Net-Sleeve Blouse",
    "slug": "berry-net-sleeve-blouse-p096",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Berry Net-Sleeve Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p096.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p097",
    "name": "Bottle Green Textured Blouse",
    "slug": "bottle-green-textured-blouse-p097",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Bottle Green Textured Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p097.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p098",
    "name": "Black Net-Sleeve Blouse",
    "slug": "black-net-sleeve-blouse-p098",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Black Net-Sleeve Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p098.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p099",
    "name": "Floral Brocade Sleeveless Blouse",
    "slug": "floral-brocade-sleeveless-blouse-p099",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Floral Brocade Sleeveless Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p099.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p100",
    "name": "White Embroidered Floral Blouse",
    "slug": "white-embroidered-floral-blouse-p100",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "White Embroidered Floral Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p100.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p101",
    "name": "Wine Peacock-Sleeve Blouse",
    "slug": "wine-peacock-sleeve-blouse-p101",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Wine Peacock-Sleeve Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p101.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p102",
    "name": "Red Peacock-Sleeve Blouse",
    "slug": "red-peacock-sleeve-blouse-p102",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Red Peacock-Sleeve Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p102.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p103",
    "name": "Mehendi Green Peacock-Sleeve Blouse",
    "slug": "mehendi-green-peacock-sleeve-blouse-p103",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Mehendi Green Peacock-Sleeve Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p103.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p104",
    "name": "Rani Pink Bandhani Blouse",
    "slug": "rani-pink-bandhani-blouse-p104",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Rani Pink Bandhani Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p104.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p105",
    "name": "Gold Crushed Blouse",
    "slug": "gold-crushed-blouse-p105",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Gold Crushed Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p105.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p106",
    "name": "Onion Pink Bandhani Blouse",
    "slug": "onion-pink-bandhani-blouse-p106",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Onion Pink Bandhani Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p106.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p107",
    "name": "Navy Blue Bandhani Blouse",
    "slug": "navy-blue-bandhani-blouse-p107",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Navy Blue Bandhani Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p107.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p108",
    "name": "Teal Green Bandhani Blouse",
    "slug": "teal-green-bandhani-blouse-p108",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Teal Green Bandhani Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p108.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p109",
    "name": "Mauve Bandhani Blouse",
    "slug": "mauve-bandhani-blouse-p109",
    "price": 12,
    "shortDescription": "Saree Blouse",
    "description": "Mauve Bandhani Blouse. Readymade saree blouse.",
    "category": "women",
    "subcategory": "Blouses",
    "fabric": "",
    "colors": [],
    "sizes": [],
    "images": [
      "/products/p109.jpg"
    ],
    "tags": [
      "new"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 1
  },
  {
    "id": "p110",
    "name": "Boys Stone-Wash Graphic Jeans",
    "slug": "boys-stone-wash-graphic-jeans-p110",
    "price": 0,
    "shortDescription": "Kids' Jeans",
    "description": "Kids Jeans - 96. Boys' denim jeans.",
    "category": "kids",
    "subcategory": "Jeans",
    "fabric": "Denim",
    "colors": [
      {
        "name": "Stone Ash",
        "hex": "#B7ADA1",
        "image": ""
      },
      {
        "name": "Stone Blue",
        "hex": "#6C7A8A",
        "image": ""
      },
      {
        "name": "Ash Grey",
        "hex": "#8C8F91",
        "image": ""
      }
    ],
    "sizes": [
      "28",
      "30",
      "26"
    ],
    "images": [],
    "tags": [
      "jeans",
      "kids",
      "denim"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 12,
    "variants": [
      {
        "size": "28",
        "color": "Stone Ash",
        "quantity": 2
      },
      {
        "size": "28",
        "color": "Stone Blue",
        "quantity": 2
      },
      {
        "size": "30",
        "color": "Ash Grey",
        "quantity": 2
      },
      {
        "size": "26",
        "color": "Stone Ash",
        "quantity": 2
      },
      {
        "size": "26",
        "color": "Stone Blue",
        "quantity": 2
      },
      {
        "size": "30",
        "color": "Stone Blue",
        "quantity": 2
      }
    ]
  },
  {
    "id": "p111",
    "name": "Boys Grey Faded Slim Jeans",
    "slug": "boys-grey-faded-slim-jeans-p111",
    "price": 0,
    "shortDescription": "Kids' Jeans",
    "description": "Kids Jeans - Trendy 99. Boys' denim jeans.",
    "category": "kids",
    "subcategory": "Jeans",
    "fabric": "Denim",
    "colors": [],
    "sizes": [
      "28",
      "30",
      "26"
    ],
    "images": [],
    "tags": [
      "jeans",
      "kids",
      "denim"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 6,
    "variants": [
      {
        "size": "28",
        "color": "",
        "quantity": 2
      },
      {
        "size": "30",
        "color": "",
        "quantity": 2
      },
      {
        "size": "26",
        "color": "",
        "quantity": 2
      }
    ]
  },
  {
    "id": "p112",
    "name": "Boys Striped-Belt Denim Jeans",
    "slug": "boys-striped-belt-denim-jeans-p112",
    "price": 0,
    "shortDescription": "Kids' Jeans",
    "description": "Kids Jeans - Red Stripe. Boys' denim jeans.",
    "category": "kids",
    "subcategory": "Jeans",
    "fabric": "Denim",
    "colors": [
      {
        "name": "Stone Ash",
        "hex": "#B7ADA1",
        "image": ""
      },
      {
        "name": "Grey Green",
        "hex": "#7C8574",
        "image": ""
      },
      {
        "name": "Navy blue",
        "hex": "#1E2A4A",
        "image": ""
      }
    ],
    "sizes": [
      "28",
      "30",
      "26",
      "22"
    ],
    "images": [],
    "tags": [
      "jeans",
      "kids",
      "denim"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 6,
    "variants": [
      {
        "size": "28",
        "color": "",
        "quantity": 2
      },
      {
        "size": "30",
        "color": "Stone Ash",
        "quantity": 1
      },
      {
        "size": "30",
        "color": "Grey Green",
        "quantity": 1
      },
      {
        "size": "26",
        "color": "Navy blue",
        "quantity": 1
      },
      {
        "size": "22",
        "color": "Navy blue",
        "quantity": 1
      }
    ]
  },
  {
    "id": "p113",
    "name": "Boys Charcoal Belted Jeans",
    "slug": "boys-charcoal-belted-jeans-p113",
    "price": 0,
    "shortDescription": "Kids' Jeans",
    "description": "Kids Jeans - RDN. Boys' denim jeans.",
    "category": "kids",
    "subcategory": "Jeans",
    "fabric": "Denim",
    "colors": [],
    "sizes": [
      "28"
    ],
    "images": [],
    "tags": [
      "jeans",
      "kids",
      "denim"
    ],
    "featured": false,
    "new": true,
    "bestSeller": false,
    "rating": 0,
    "reviews": 0,
    "stock": 2,
    "variants": [
      {
        "size": "28",
        "color": "",
        "quantity": 2
      }
    ]
  }
];

export const collections = [
  { id: 'men',    title: "Men's",   subtitle: 'Shirts & sweaters', description: 'Shirts, polos and knitwear for every day.', image: '' },
  { id: 'women',  title: "Women's", subtitle: 'Tops & occasion',   description: 'Tops, blouses, sarees and set mundu.',      image: '' },
  { id: 'kids',   title: 'Kids',    subtitle: 'Everyday wear',     description: 'Shirts, crop tops and denim for children.', image: '' },
  { id: 'unisex', title: 'Unisex',  subtitle: 'Shared styles',     description: 'Pieces cut to suit everyone.',              image: '' },
];

/**
 * Stand-in colourway. Most pieces in the export have no colour recorded, so
 * anything reading colors[0] must fall back rather than crash.
 */
export const DEFAULT_COLOR: ProductColor = { name: 'As shown', hex: '#B8B2A8', image: '' };

/** The chosen colourway, or the stand-in when none are recorded. */
export function colorAt(p: Product, index = 0): ProductColor {
  return p.colors[index] ?? p.colors[0] ?? DEFAULT_COLOR;
}

/** True when the piece has no price set yet — show price-on-request. */
export function isUnpriced(p: Product): boolean {
  return !p.price || p.price <= 0;
}

/**
 * Units available for a size + colour. Uses the variant matrix when the product
 * has one; otherwise falls back to the single stock number (or treats stock as
 * unset → available, so pre-variant products still sell).
 */
export function variantStock(p: Product, size: string, color: string): number {
  if (p.variants && p.variants.length) {
    const match = p.variants.find((v) => v.size === size && v.color === color);
    return match ? match.quantity : 0;
  }
  return typeof p.stock === 'number' ? p.stock : Infinity;
}

/** Total units across the variant matrix, or the flat stock number. */
export function totalStock(p: Product): number {
  if (p.variants && p.variants.length) {
    return p.variants.reduce((n, v) => n + v.quantity, 0);
  }
  return typeof p.stock === 'number' ? p.stock : 0;
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts(list: Product[] = products): Product[] {
  return list.filter((p) => p.featured);
}

export function getProductsByCategory(category: Product['category'], list: Product[] = products): Product[] {
  return list.filter((p) => p.category === category);
}

export function getClearanceProducts(list: Product[] = products): Product[] {
  const customClearance = list.filter((p) => p.clearance && p.originalPrice && p.originalPrice > p.price);
  if (customClearance.length > 0) {
    return customClearance.sort((a, b) => discountPercent(b) - discountPercent(a));
  }
  return list.slice(0, 8).map((p, idx) => ({
    ...p,
    price: p.price || Math.round(45 + (idx * 12)),
    originalPrice: p.originalPrice || Math.round((p.price || (45 + (idx * 12))) * 1.4),
    clearance: true,
  }));
}

/**
 * Authentic traditional Onam / Kerala festival wear already in the catalogue —
 * set mundu, pattupavada, sarees and dhavani sets. Pulled by subcategory so it
 * tracks the real stock; nothing is invented.
 */
export function getOnamProducts(list: Product[] = products): Product[] {
  const onamTypes = new Set(['Mundu', 'Sarees', 'Blouses']);
  return list.filter((p) => onamTypes.has(p.subcategory));
}

export function discountPercent(p: Product): number {
  if (!p.originalPrice || p.originalPrice <= p.price) return 0;
  return Math.round(((p.originalPrice - p.price) / p.originalPrice) * 100);
}

export function formatPrice(price: number): string {
  if (price % 1 === 0) return price.toString();
  return price.toFixed(2);
}

export const testimonials: {
  id: string; name: string; location: string; text: string; rating: number; product: string;
}[] = [];
